{{- define "configMap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snyk-broker.fullname" . }}-{{ .name }}{{ if not .Values.disableSuffixes }}-{{ .Release.Name }}{{ end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . | nindent 4 }}
data:
  {{ .Key }}: {{ .Value | nindent 2 }}
{{- end }}

{{- if .Values.httpsCert }}
{{- include "configMap" (dict "name" "httpscert-configmap" "Key" "" "Value" (.Files.Glob .Values.httpsCert).AsConfig) }}
{{- end }}