apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app1
spec:
  type: ExternalName
  externalName: app.snyk.io
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
      haproxy.org/server-ssl: "true"
      haproxy.org/backend-config-snippet: |
        # See this article for the deep reasons of both parameters: https://www.haproxy.com/fr/blog/http-keep-alive-pipelining-multiplexing-and-connection-pooling/
        # enforce SNI with the Host string instead of the 'Host' header, because HAProxy cannot reuse connections with a non-fixed Host SNI value.
        default-server check-sni app1.example.com sni str(app1.example.com) resolvers mydns resolve-prefer ipv4
        # make HAProxy reuse connections, because the default safe mode reuses connections only for the same source.ip
        http-reuse always

spec:
  rules:
  - host: app1.example.com
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: 443