{{- if .Values.brokerToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.scmBrokerTokenName" . }}
type: Opaque
data:
  "{{ .Values.scmType}}-broker-token-key": {{ .Values.brokerToken | b64enc | quote }}
---
{{- end }}
{{- if .Values.scmToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.scmTokenName" . }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.scmToken | b64enc | quote }}
{{- end }}
---
{{- if .Values.scmTokenPool }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.scmTokenPoolName" . }}
type: Opaque
data:
  "{{ .Values.scmType }}-token-key-pool": {{ .Values.scmTokenPool | b64enc | quote }}
{{- end }}
---
{{- if .Values.bitbucketPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.scmTokenName" . }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.bitbucketPassword | b64enc | quote }}
---
{{- end }}
{{- if .Values.bitbucketPat }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.scmTokenName" . }}
type: Opaque
stringData:
  "{{ .Values.scmType}}-token-key": {{ .Values.bitbucketPat | quote }}
---
{{- end }}
{{- if .Values.azureReposToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.scmTokenName" . }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.azureReposToken | b64enc | quote }}
---
{{- end }}
{{- if .Values.jiraPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.scmTokenName" . }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.jiraPassword | b64enc | quote }}
---
{{- end }}
{{- if .Values.jiraPat }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.scmTokenName" . }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.jiraPat | b64enc | quote }}
---
{{- end }}
{{- if .Values.crPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.scmTokenName" . }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.crPassword | b64enc | quote }}
---
{{- end }}
{{- if .Values.crToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.scmTokenName" . }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.crToken | b64enc | quote }}
---
{{- end }}
{{- if .Values.snykToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.snykTokenName" . }}
type: Opaque
data:
  "snyk-token-key": {{ .Values.snykToken | b64enc | quote }}
---
{{- end }}
{{- if .Values.artifactoryUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.artifactoryUrlName" . }}
type: Opaque
stringData:
  artifactory-url: {{ .Values.artifactoryUrl | quote }}
---
{{- end }}
{{- if and (.Values.artifactoryUrl) (.Values.brokerClientValidationUrl) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.artifactoryValidationUrlName" . }}
type: Opaque
stringData:
  artifactory-broker-client-validation-url: {{ .Values.brokerClientValidationUrl | quote }}
---
{{- end }}
{{- if .Values.baseNexusUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.nexusBaseUrlName" . }}
type: Opaque
data:
  "nexus-base-nexus-url": {{ .Values.baseNexusUrl | b64enc | quote }}
---
{{- end}}
{{- if .Values.nexusUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.nexusUrlName" . }}
type: Opaque
data:
  "nexus-nexus-url": {{ .Values.nexusUrl | b64enc | quote }}
---
{{- end}}
{{ if or (.Values.baseNexusUrl) (.Values.nexusUrl) }}
  {{- if .Values.brokerClientValidationUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.nexusValidationUrlName" . }}
type: Opaque
stringData:
  nexus-broker-client-validation-url: {{ .Values.brokerClientValidationUrl | quote }}
---
  {{- end }}
{{- end }}
{{- if and (.Values.httpsCert) (.Values.httpsKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.tlsSecretName" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ (.Files.Get .Values.httpsCert) | b64enc | quote }}
  tls.key: {{ (.Files.Get .Values.httpsKey) | b64enc | quote }}
---
{{- end }}
{{- if or .Values.caCert .Values.caCertFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.caCertSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . | nindent 4 }}
data:
{{- if and .Values.caCert (not .Values.caCertFile) }}
{{ (.Files.Glob .Values.caCert).AsSecrets | nindent 2 }}
{{- else if and .Values.caCertFile (not .Values.caCert) }}
  cacert: {{ .Values.caCertFile | trim |  b64enc | nindent 4}}
{{- end }}
---
{{- end }}
