{{ $suffix := ( .Values.disableSuffixes | default false ) | ternary "" ( printf "-%s" .Release.Name ) }}
{{- if and .Values.brokerToken .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-broker-token{{ $suffix }}
type: Opaque
data:
  "{{ .Values.scmType}}-broker-token-key": {{ .Values.brokerToken | b64enc | quote }}
---
{{- end }}
{{- if and .Values.scmToken .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token{{ $suffix }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.scmToken | b64enc | quote }}
{{- end }}
---
{{- if and .Values.scmTokenPool .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType }}-token-pool{{ $suffix }}
type: Opaque
data:
  "{{ .Values.scmType }}-token-key-pool": {{ .Values.scmTokenPool | b64enc | quote }}
{{- end }}
---
{{- if and .Values.bitbucketPassword .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token{{ $suffix }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.bitbucketPassword | b64enc | quote }}
---
{{- end }}
{{- if and .Values.bitbucketPat .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token{{ $suffix }}
type: Opaque
stringData:
  "{{ .Values.scmType}}-token-key": {{ .Values.bitbucketPat | quote }}
---
{{- end }}
{{- if and .Values.azureReposToken .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token{{ $suffix }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.azureReposToken | b64enc | quote }}
---
{{- end }}
{{- if and .Values.jiraPassword .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token{{ $suffix }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.jiraPassword | b64enc | quote }}
---
{{- end }}
{{- if and .Values.jiraPat .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token{{ $suffix }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.jiraPat | b64enc | quote }}
---
{{- end }}
{{- if and .Values.crPassword .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token{{ $suffix }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.crPassword | b64enc | quote }}
---
{{- end }}
{{- if and .Values.crToken .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token{{ $suffix }}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.crToken | b64enc | quote }}
---
{{- end }}
{{- if and .Values.snykToken .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: snyk-token{{ $suffix }}
type: Opaque
data:
  "snyk-token-key": {{ .Values.snykToken | b64enc | quote }}
---
{{- end }}
{{- if and .Values.artifactoryUrl .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-url{{ $suffix }}
type: Opaque
stringData:
  artifactory-url: {{ .Values.artifactoryUrl | quote }}
---
{{- end }}
{{- if and (.Values.artifactoryUrl) (.Values.brokerClientValidationUrl) .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-broker-client-validation-url{{ $suffix }}
type: Opaque
stringData:
  artifactory-broker-client-validation-url: {{ .Values.brokerClientValidationUrl | quote }}
---
{{- end }}
{{- if and .Values.baseNexusUrl .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: nexus-base-nexus-url{{ $suffix }}
type: Opaque
data:
  "nexus-base-nexus-url": {{ .Values.baseNexusUrl | b64enc | quote }}
---
{{- end}}
{{- if and .Values.nexusUrl .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: nexus-nexus-url{{ $suffix }}
type: Opaque
data:
  "nexus-nexus-url": {{ .Values.nexusUrl | b64enc | quote }}
---
{{- end}}
{{ if or (.Values.baseNexusUrl) (.Values.nexusUrl) }}
  {{- if and .Values.brokerClientValidationUrl .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: nexus-broker-client-validation-url{{ $suffix }}
type: Opaque
stringData:
  nexus-broker-client-validation-url: {{ .Values.brokerClientValidationUrl | quote }}
---
  {{- end }}
{{- end }}
{{- if and (.Values.httpsCert) (.Values.httpsKey) .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.tlsSecretName" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ (.Files.Get .Values.httpsCert) | b64enc | quote }}
  tls.key: {{ (.Files.Get .Values.httpsKey) | b64enc | quote }}
---
{{- end }}
{{- if and (or .Values.caCert .Values.caCertFile) .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-broker.caCertSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . | nindent 4 }}
data:
{{- if and .Values.caCert (not .Values.caCertFile) }}
{{ (.Files.Glob .Values.caCert).AsSecrets | nindent 2 }}
{{- else if and .Values.caCertFile (not .Values.caCert) }}
  cacert: {{ .Values.caCertFile | trim |  b64enc | nindent 4}}
{{- end }}
---
{{- end }}
