{{- if ( and .Values.serviceAccount.create .Values.serviceAccount.enabled ) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snyk-broker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
